### ISSUE TITLE
Why are there many more samples in the metadata file than the OTU table?

### ISSUE THREAD

**Issue by tanaes** [FloMazel/Microbiome_Phylo_Diversity_Workshop#2]
It might be nicer for some of the visualizations and statistics to use a few more samples. Are we running into file size limitations?

**Comment by FloMazel** [comment]
No we do not -- I think this is what the dataset they end up with in mothur/qiime2 workshop (https://github.com/EDUCE-UBC/workshops/tree/master/data). I can ask them if they have more.

**Comment by tanaes** [comment]
I think that's fine, then. Nice to use the same data! Working on running through PhyloFactor now, so we'll see.
